# -*- Dockerfile -*-

FROM debian/eol:etch

ARG R_VERSION

ENV PAGER=less

RUN apt-get update && \
    apt-get install -y linux32 wget ca-certificates && \
    echo 'deb http://ppa.r-pkg.org/evercran etch main' \
         >> /etc/apt/sources.list && \
    wget -O- http://ppa.r-pkg.org/rhub.gpg.key | apt-key add - && \
    apt-get update -y && \
    apt-get install -y r-${R_VERSION} && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    mkdir -p /var/lib/apt/lists/partial

RUN ln -s /opt/R/${R_VERSION}/bin/R /usr/local/bin/

RUN if [ -f /opt/R/${R_VERSION}/bin/Rscript ]; then               \
        ln -s /opt/R/${R_VERSION}/bin/Rscript /usr/local/bin/;    \
    fi

# Some old versions do not have --vanilla
RUN (echo 'library()' | /opt/R/${R_VERSION}/bin/R --vanilla | cat) || \
    (echo 'library()' | /opt/R/${R_VERSION}/bin/R | cat)

WORKDIR /root

COPY cran.txt /tmp/cran.txt
COPY set-cran.sh /tmp/set-cran.sh
RUN R_VERSION=${R_VERSION} /tmp/set-cran.sh

COPY etch-entrypoint.sh /usr/local/bin/entrypoint.sh
ENTRYPOINT [ "/usr/local/bin/entrypoint.sh" ]

CMD [ "R" ]
