# -*- Dockerfile -*-

FROM debian/eol:sarge

ENV PAGER=less
ENV LESS=-r

RUN echo 'deb http://ppa.r-pkg.org/evercran sarge main' \
    >> /etc/apt/sources.list

COPY prerelease-versions.txt .

RUN apt-get update && \
    apt-get install -y linux32 `cat prerelease-versions.txt | sed 's/^/r-/'` && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    mkdir -p /var/lib/apt/lists/partial && \
    rm prerelease-versions.txt

WORKDIR /root

ENTRYPOINT [ "linux32" ]
CMD [ "bash" ]
