# -*- Dockerfile -*-

FROM debian/eol:wheezy

ARG R_VERSION

ENV PAGER=less

RUN apt-get update && \
    apt-get install -y linux32 wget ca-certificates && \
    wget https://github.com/r-hub/R/releases/download/v${R_VERSION}/r-evercran-debian-7.11-${R_VERSION}_1-1_i386.deb && \
    dpkg -i r-evercran-debian-7.11-${R_VERSION}_1-1_i386.deb || true && \
    apt-get -fy install && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    mkdir -p /var/lib/apt/lists/partial

RUN ln -s /opt/R/${R_VERSION}/bin/R /usr/local/bin/

RUN if [ -f /opt/R/${R_VERSION}/bin/Rscript ]; then               \
        ln -s /opt/R/${R_VERSION}/bin/Rscript /usr/local/bin/;    \
    fi

# Some old versions do not have --vanilla
RUN (echo 'library()' | /opt/R/${R_VERSION}/bin/R --vanilla | cat) || \
    (echo 'library()' | /opt/R/${R_VERSION}/bin/R | cat)

WORKDIR /root

ENTRYPOINT [ "linux32" ]
CMD [ "R" ]
